//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }

        [DisplayName("ID")]
        public int Id { get; set; }
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "El nombre es un campo requerido")]
        public string Nombre { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "El email es un campo requerido")]
        [EmailAddress(ErrorMessage = "El formato de email es inválido")]
        public string Email { get; set; }
        [DisplayName("Fecha de nacimiento")]
        [Required(ErrorMessage = "La fecha de nacimiento es un campo requerido")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Nacimineto { get; set; }
        [DisplayName("Teléfono")]
        [Required(ErrorMessage = "El teléfono es un campo requerido")]
        [Phone(ErrorMessage = "El teléfono es inválido")]
        public string Telefono { get; set; }
        [DisplayName("Dirección")]
        [Required(ErrorMessage = "La dirección es un campo requerido")]
        public string Direccion { get; set; }
        [DisplayName("País")]
        [Required(ErrorMessage = "El país es un campo requerido")]
        public string Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Pedidos")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
