//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Detalles_Pedido
    {
        public int Id { get; set; }
        [DisplayName("ID Pedido")]
        [Required(ErrorMessage = "El ID del pedido es un campo requerido")]
        public int Id_Pedido { get; set; }
        [DisplayName("ID Producto")]
        [Required(ErrorMessage = "El ID del producto es un campo requerido")]
        public int Id_Producto { get; set; }
        [DisplayName("Unidades")]
        [Required(ErrorMessage = "Las unidades es un campo requerido")]
        public int Unidades { get; set; }
        [DisplayName("Precio unitario")]
        [Required(ErrorMessage = "El precio unitario es un campo requerido")]
        public decimal Precio_Unitario { get; set; }
        [DisplayName("IVA")]
        [Required(ErrorMessage = "El IVA es un campo requerido")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal IVA { get; set; }

        [DisplayName("Pedido")]
        public virtual Pedidos Pedidos { get; set; }
        [DisplayName("Producto")]
        public virtual Productos Productos { get; set; }
    }
}
