//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.Detalles_Pedido = new HashSet<Detalles_Pedido>();
        }

        [DisplayName("ID")]
        public int Id { get; set; }
        [DisplayName("ID Cliente")]
        [Required(ErrorMessage = "El ID del cliente es un campo requerido")]
        public int Id_Cliente { get; set; }
        [DisplayName("ID Estado")]
        [Required(ErrorMessage = "El ID del estado es un campo requerido")]
        public int Id_Estado { get; set; }
        [DisplayName("Fecha del pedido")]
        [Required(ErrorMessage = "La fecha del pedido es un campo requerido")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public System.DateTime Fecha_Pedido { get; set; }
        [DisplayName("Fecha de modificación")]
        [Required(ErrorMessage = "La fecha de modificación es un campo requerido")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public System.DateTime Fecha_Modificacion { get; set; }

        [DisplayName("Cliente")]
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Detalles")]
        public virtual ICollection<Detalles_Pedido> Detalles_Pedido { get; set; }
        [DisplayName("Estado")]
        public virtual Estados_Pedido Estados_Pedido { get; set; }
    }
}
