//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalles_Pedido = new HashSet<Detalles_Pedido>();
        }

        [DisplayName("ID")]
        public int Id { get; set; }
        [DisplayName("ID Categoría")]
        [Required(ErrorMessage = "El ID de la categoría es un campo requerido")]
        public int Id_Categoria { get; set; }
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "El nombre es un campo requerido")]
        public string Nombre { get; set; }
        [DisplayName("Descripción")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "La descripción es un campo requerido")]
        public string Descripcion { get; set; }
        [DisplayName("Imagen")]
        public string Imagen { get; set; }
        [DisplayName("Catálogo")]
        [Required(ErrorMessage = "El catálogo es un campo requerido")]
        [Range(0, int.MaxValue)]
        public int Catalogo { get; set; }
        [DisplayName("Precio unitario")]
        [Required(ErrorMessage = "El precio unitario es un campo requerido")]
        [DataType(DataType.Currency)]
        public decimal Precio_Unitario { get; set; }
        [DisplayName("IVA")]
        [Required(ErrorMessage = "El IVA es un campo requerido")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal IVA { get; set; }
        [DisplayName("Escaparate")]
        [Required(ErrorMessage = "El escaparate es un campo requerido")]
        public bool Escaparate { get; set; }

        [DisplayName("Categoría")]
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Detalles")]
        public virtual ICollection<Detalles_Pedido> Detalles_Pedido { get; set; }
    }
}
